apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
#  namespace: netology
spec:
  ports:
    - name: http-nginx
      port: 9001
      protocol: TCP
      targetPort: 80
    - name: http-multitool
      port: 9002
      protocol: TCP
      targetPort: 8080
  selector:
    app: web